{% set name = "ipython_unittest" %}
{% set version = "0.3.1" %}
{% set sha256 = "817c540b7efb1dc510fff9af6ad283ed85252096a3e41a4b091e2f6d04eee1c6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - ipython
    - ipykernel

test:
  imports:
    - ipython_unittest

about:
  home: https://github.com/JoaoFelipe/ipython-unittest
  license: MIT
  license_family: MIT
  summary: 'Add unittest cell magics to IPython for easily running tests'

  # The remaining entries in this section are optional, but recommended
  description: |
    This extension provides testing support to IPython through cell magics.
    Currently, we have three magics that transforms the cell code and executes unittest:
    `%%unittest_main`, `%%unittest_testcase` and `%%unittest`;
    one magic to run external tests: `%%external`;
    and one associated magic to write external files: `%%write {mode}`
  dev_url: https://github.com/JoaoFelipe/ipython-unittest

extra:
  recipe-maintainers:
    - JoaoFelipe
