# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R4htt1vNyeFG9FN8T/hQRnd12y/7ROSL8aOv8lihHIII+aTT1jebNTl9Wi7Kt/2mekYFp5rsAeJptG+mcwNUCaELafYLOd3NbLq3+f36hnfRupwx3wU1yICSlcdaIUWCKL9dfndQVyz9+o04DxCBmIUpBPonXHcqd72Cb47+/h4zriRIJFfT3ZJERJv32ewtTe29S4m+t5QWbng3fR+8+Rt2lTZ49LsngEuV32HoiR9Pz8WvgxXCdlxMGUbw6wKSVqFluG/tuyLh21vFF36CzXUSZwxlws5jWSLXOPYREQkl0xofK6EYSw5pGmEb+fV5FV9FQHRhWd5zGKFHEWTtSsAZ6OGhawEa2oVudg6VnCTAJ+Qgiaqrdpyj/v4HvpjpH5SR5wE/4fYhL+BOQIf0wcP2ptgbcweDLq7aLy7gZsNwaB0lkzVJtLrEowYrw6KjmURvuLTZAO+FmzKKG2azkkIw4t/5LzWrehPsH+O1AwEZYMxlQ3ik6F6aVy2tbfBfxSDDNfa+IEuYsZC5f/8nTrJsZWznwnJx3jeAaER2ICYm4pZneTZg6+hWOBlLJeOexcXpRlVPbKZM7SiI1BgAR1PgqaylK5V0q7CHkyUaPyuh5XYnMNU05oIr/DrV5PqWZwZzTmsWj/2MB5sLL9io7hzEczFS+BNkuhnq8zq3Sbk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
