travis:
  secure:
    BINSTAR_TOKEN: R4htt1vNyeFG9FN8T/hQRnd12y/7ROSL8aOv8lihHIII+aTT1jebNTl9Wi7Kt/2mekYFp5rsAeJptG+mcwNUCaELafYLOd3NbLq3+f36hnfRupwx3wU1yICSlcdaIUWCKL9dfndQVyz9+o04DxCBmIUpBPonXHcqd72Cb47+/h4zriRIJFfT3ZJERJv32ewtTe29S4m+t5QWbng3fR+8+Rt2lTZ49LsngEuV32HoiR9Pz8WvgxXCdlxMGUbw6wKSVqFluG/tuyLh21vFF36CzXUSZwxlws5jWSLXOPYREQkl0xofK6EYSw5pGmEb+fV5FV9FQHRhWd5zGKFHEWTtSsAZ6OGhawEa2oVudg6VnCTAJ+Qgiaqrdpyj/v4HvpjpH5SR5wE/4fYhL+BOQIf0wcP2ptgbcweDLq7aLy7gZsNwaB0lkzVJtLrEowYrw6KjmURvuLTZAO+FmzKKG2azkkIw4t/5LzWrehPsH+O1AwEZYMxlQ3ik6F6aVy2tbfBfxSDDNfa+IEuYsZC5f/8nTrJsZWznwnJx3jeAaER2ICYm4pZneTZg6+hWOBlLJeOexcXpRlVPbKZM7SiI1BgAR1PgqaylK5V0q7CHkyUaPyuh5XYnMNU05oIr/DrV5PqWZwZzTmsWj/2MB5sLL9io7hzEczFS+BNkuhnq8zq3Sbk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
