travis:
  secure:
    BINSTAR_TOKEN: Pm/55P79CwPE1eZH7IR4T+CV6025i8VYkt6r9DH9jYPXhwiaMdgi6PxCdHVb8UK8SrsZsyQytxDEXUAj5zJEzOoQZ0W1x35AlngSh5n7REzRvbmvlLcKLL6FaRvmggMLbAvS13ySePSo5IY39egsgJ+VoxhYqH977n4i4eCFI6t9oPGBE2pAyC9PwfSV28mFX6dE96d9OdHgJj91RCbOT4kfzJnKy5pD9gVOY4OymlRye4dEm+C4FCqdLRbjdt5kb+Lj0fiOS1i2jzz/VC9jb/2gWg5Bs3Ocvj6+F/BdHoxHAWdlMZiyLrzQmphrUOXnXRo/L6Jjxs2Wg87XZjm4R0+fhHgETWQDO+0LCMbDxXbvwCOQGMfv48qmGfeNpB9RmY/wakZRRBCSNjfU17bDvgN+9sRjcptnXyUyNgUBoe4IVYQ0SwniFEcp5OhxaPjWcOlQOGBbyfnH6xMs2zr0fMTmlq7BfXUtJ1Jf0QGot0PycjefjRYfeh0eJPid9cuNxODa3kBNgtPeLv4rQm3UrNGmsEeXUhTqabaEtM2z9afA8+Aa0BVdx8vYkPZ3DHguuk9iIowuiKTBkhL2RZPsP4to4ZyikFlqvBqQoqTvUuTiYWfzufiv1cDzhmuJc1jFEzdSAscs3JIw12VL7LSwDB/pPycqJcozmV3jwvgDIIU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
