travis:
  secure:
    BINSTAR_TOKEN: L3iQwo/t1bKrYj/3xqo7+UPAlFRL6iduFBfwcGv+sn4KTd/10ZsR1b62nH9/3IeOKIxFpuNsk5QcAqgugYJNVZ1RQWwRjubVPHmz6Xte0sALv6EOQlernsUuHTa9ibe67rWLgfM16ueh8x04lSEC7QSPsPKHK3JWrChsdKR6nrv6uwwyR9rKEA2wflyXlh0n4zBQmCPfJWQXaQ4AsheL7/0TuYDcDn6Whc+fHbJYNzv29+tJn8R41QYJkfwJHdGQPdHwf85c8qPs4vM0xh8ovQoPG2H4tnTAeyxvXuTVK19Ws+cnmoJ978IDoYhu1QwjpRsahCrswPzbvnPbmRgAtTCMX+22T/NNRUCe/Dq43inFThHKyOT1gT6E6EwLKflUfxRtwDCWqcneTbG0TlCryWwspnJGW9VIs0xSDUiqH/iq9e3MS+oZ9IQN8gMqk+pDO1vR4RT7GktZ7KwcgTHkTw2gybZc0g60zupSSC5LzWL0XUjObIgivDU6Egl+JP7QNKixJa2f3gyzpaisV4SHS6YN2+pQxSIVsP7fhAdg5Q1jkDr8qSaXMyywitwKZ/PAGbtKWl4N1YnA7RaZwsp6Y0yZqgirvZON6pLYqJ7GnpolJXhXNCqLM5PhUN7nieCGfvzipMIeIo6R1KZd0HxRstxUoKRR2/7Zn1m9aoX6bXk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
