travis:
  secure:
    BINSTAR_TOKEN: ny+Sv2LvHfO1NcV9ySYZx2r3lKBaKZOHCVhzwFcPWi6F2cNkD44fW3hCq28C6aN+yNITQndPfSgcVAs1NEn2FPwLHODaOdeTTQtidpBxspdpqdWckwEdBvXE7ZxkaZaR09Np4JiGZTcVp4zO1KI7CgC9bFSrHYtRMrjMHSn/INb2mQOp45innp34vJkegIQRj2RnGU8nCVdtLuY4fecarvu8JIpQe2m07TRJJBwL9x+ELdsc2o63fanESkeHCJJIoQxIDt/BPY/AMYZSjBQNZb1iPRRHOWG90uaJK/5WhcrJua239EwzEvKkwsHEwclUNA1t3ksBhX/XDvFX0QmTI7Ne02dip6pjEV7U/IxLfcTphDhWSXoVfQktyevwS0OKd3wj7/TgoDouU+/bFeTNLQ6J4f2GmLgyapWG7KUMfpqT63ZRgfmXNnmVEL0o5hojGhq7N0JzlImPvmEZ8OjMi/CWomrvyXp0rdzIhhPPISXgt3EJNAVFUdgf7cfQIz/24FJwe6Xatts6cWb0AKzsvHvqP4QOmYI0mkRkgufgtgzu5H35+3LX6uv6X8UxkrKh38Yz0CXWAaPhV4QZ7aSDcWwCPEdVyFOJokGnluprzOEG/8JkM8M+RAKAiHMCFo/IIMIxGRPcspIev5McpmSPa433HuOBz7rUrT6OlzDsXYs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
