travis:
  secure:
    BINSTAR_TOKEN: J3GvYoi1WfrUHoCgmM3jvDXuGKlbCGmsnLWh5B0KgQFycC9J2SS36iSSRXklBWQkD6h9oowar5alTy9/bz/c+86WSa8A47rqQ4/etqbFYL/uEabNECm+heXnxURyxlJVijQ25ukapeXmx/UxTM5jBYUwo389pVAx8ryldYQgwk64pCDwe1ly42ZmWvs0Sai1zZy9Fo57jtHOy9lw3MXQYWj2iITJKh4FWPzdMKVsi/mqd9DIS87BhP8QUpI0FuaZvFP150mw2XOznwX6YQo55ep9vWm2gukpj6bsT2uOPw95tmZQBDq+fDcUQfCXsWbhP7Q3RTlZtSKtLXLFoJA9FfoKSWYtUPGbrowEM7gmU/zUBzgzKpdONxlCM9rBODX65vcagziwWb/sDzRnhIXtb5BHq7jVvmes2lxfdP/oE39AzqLZe5XVmpG1D6FY0Fy4FfHQlgY5tJ5bxnoBC+0QoN+V1PMPntq6IaAxwMW28gBjlGi/Nd0SDs+RzLiRLOzEoFxvq2bMs2N2Y3zH4+9xq0MWPQzBjVdq8KSUKk2Fvo2TJw6KbK5Gkz6yvnYFsVddXFGa6zp3H4SA8fCcmEodHjUnoAT2w4QdjR0A/UmhyNtpqBewdpDZg04B0MTDa1qgDkGfCqk2cTwzSV8yf6nFO1RSkaaZ6/+5CTNjGPp9JaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
