travis:
  secure:
    BINSTAR_TOKEN: RPdl7cSWLwf5ls0ARHydelIqcPubw8Mogz1rbLuXxhZyyh8967L6AT3ZPXG7zC9YnZE1CVmg4jagbSL4PyYaG+rcef6retEZRfSsUVmIshaPbcPg0wuUFAGm+OOm4t/xE4fX0HnvMTyrv/+l0/04igN+wORTsGJp0jEGaf99nD6+kxuaAh2SyiJIqM5xTWDfhOgK4C9wsscogTD/iI0u04OvoYEeSZCvOrjnUuebOe3rWDIRNaWLFhKQxsRLJfnE/UpElnsE5lZgbOXc42uX97+O7twTlN9Ymv4l4L4udZb64H4RTRs3AaU9AKtLnd5sSRIr1W1Yp1yUajrMSKp8qmOHxWcVZ7LMdByRL0sCe61utnO8Gj9D6YdfJeSlhaYL1MF1pX3wOHkQEGemnZRwN7dVQ62SRgYtg7IQYa6thzNGq6q3Z+5sblQWAFob6vWUuVaPw7SMHHA0VNiuJiIw6PyVbes0F2JiQtDz+omaJsC1csFAXNXXT9U4f1Z/w9lYkBQEjoFqdxvJbycAY3lpe5AeOSRw7S3p+X4+wyxzUY9q9DLSFJbX9t2kiSOrujbK4/b/97IIVU3Q1lFsopMbZTd53lU1Fbrm+8V2JM+WOOadw8ZqIArfVUI66EU41xSDox0JUPGbTtQBNe6/fSHBkfHM21jqHAywy7Gdopf1aEg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
