travis:
  secure:
    BINSTAR_TOKEN: bWi7Jkwz4QW7qV+Lk+GJIIpux0x9OCoEwJL2puqxuxi62HJOQjXJ3gaAtK+C1pFl9pVjml+Ls7TVNy9CyjSVXP8chxhgUbJl4OXVj88F40IsuZmXGjR3WH6DuLDlhsanK1BaWlQqSgvhPkmfnwjaVFB01WHiJ6aGPSgQo9Ts0bwO1VBp1Cu+l8YojE8FdbDI1CWkUTlolKMQibJeAh1Nb1oWWdqMaEV2DRL6U9j/7yeQDkR/gW80faa2zkyvpKNWGhyL8rwDuAt3xufWrc7NgvtfSEdPd20++eXB7kNDzoLn6fUTqd3INw43UN70H0ddIdR2ryj5BZYKiLD7aDv7E/P/rH7CbjuXhV1rJy8sliLzBvNIYoQtJIW/CMpp/cqSHq6/TAPB8saI+DYb2KHRNBBwCf7GlPOZ6cBEYK7MfJgPqrekeZxcytVJSTppr66zD1aB+7QqcwyKTrmfgL2qEkjSPx2kf3BmzEgulaU8a8WGsf33QH+3sXV4oQ4fP+MGjHaxbHcZDNnTt8Qq/hHB2Qlv54QGLetZ9PEhF4Mg6TP8CYqt80Tih1ByndacqD13MVrBdHqn59hJTFPJfQPtR9zGqHNSLW5V0boR/aGqewgC5gFgfTmaUMmadm/LkkgLLwZJcKRDUU7+/gGm2Dg1WxNzyOb+Y1/oFHILekXEk/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
