travis:
  secure:
    BINSTAR_TOKEN: Kwp2aR8demkYNFAuttciQY8nFzykCKFB0R7xjOzxmcBD21D8VvSyF7FFG3fuxT8T6+A5/IwNA9xF0CIJ9q2yjDeLRRf29E7DIQ8VaT2rI/BbXTswEzZ8MUUYYBrBihIsKuvajHbaTQQ/fM4Y3O879uNcnuqBTIRJPiXEYb14sqbCE+XLIxZVypma+xSemSz/uA0eRfu787Y/wlrKLp5gAyHEZQyUnj29PTdU2cUf2urmslaQ7+oFdjv3ZNhnACCz8V1da78I8u6ICxWEA1TgJWmtvw4JeNFek19ggpxEuuWCXQ2Jj3fO2ARDcVeJseJeimSyF+Tp///4MjB4XdBpoxnmOKbHl2hnybTT2OB2Dl6/W+9iX2Inh/i22Bfp2jpfQyvbNt8jSizWfkWvnoV1fCwZoOT9M4c+yvGY1aYbBLETJKnVu1VOhRbM5B4I/S2FIiqudYNTgw83jx4Fgzs6GvF6U8DDqsyRkxjNCJRStpIi1hiTA8EDX5SSpQtGBvX6g8hnNEKEQJ7j/asQjmcpkXmA2V7vxHlNrj5Jt9xN8Ceo7Ywgctmttw3X4AHnGi9TMN9uKRo9k+WiQhJsYjsE940MBSNtotcC/WuNDWJDaTiQEWWjPo9TI9nxUBpJx8C/u0MVlSYGXOSIIMEkngHFJykkzVeVtJz5TNJZvu+WMYE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
