travis:
  secure:
    BINSTAR_TOKEN: FbOcyyyrwoi6MCG8nILrruckOA9t63WTm5w5kNlBCG3qhUrd/xqW8Yg/MlwL/03FGd3Ha/Je6jnTqKTnVKtVXknKIbiOad16+k6gjbc8H4FwaXTVUV5VLAFmSf+aH7CCGb8RLkfAgnaJKJe90pPkFaiclqo7BQZkELBT0wskYNVT6M1apMB8ahkBnH5HrgEPfE4Jv11xCYWKDmPM3OQZba7trxUb1PcLnENYi6hBmnwnBpvigwiFz0qvPJIqeKAWcJgzJBqBvicIte21zN9PLUgyBwuNdBTwkcPXvCOKQURWKOszaQSlPvaggQairbnPnFv2nO/CTuDtufclRPhla3meacBODo3vWcOATcd9g5FZzOGY3NjboVixfnd+uNSvi+FBOXoEEPC1diTbh9wEu4WR0r3VHJNp2wUUYseF491bMHNa7n2rDt45f0TFG1lvA82w0tnh3cTu70yGfBmF2zGPXuJP291MJrVBIeWuKA1cEDrWTf0eBROZ2vfiMHSeWzslyFCf62Hl3uphON0XwO9ddCrKsnYeZBD4jP/x/gCSm4dQktw9DJif7DtHhORyErNRWJ4FWkO5s3TD+Sf6UZYC9BGj9RHkeOTjz2ypf/Yxo10GS9s1NYdBFzGkqYTgMuv++zo0TO8oo8DpmqVlj6gvLrgefg0j8iQ3Xu+x6bI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
