travis:
  secure:
    BINSTAR_TOKEN: Fo1Fierc/BzEz/HYCZa8Mup9ZNzNlzhlcF9svtt1qwK/btecoEqa0CZvBFZwOaAzRZZEcik1VduTeJr1w37e+oEfzpO6q0NmBbmJCPNndP1hNtW49W1v7zgQ1CKAvr9qJNGcTuVHE3r06M/859ssQUoZdH81VxO2yhvYgtZf/JwteysiH6dsVX2RONrSNKAxeNxclI6VYNI2N5IvfWQVWJzgvRNP5jQAq2RM1FElNGCFw4TTy63QNf1+iJL/jwShFmXl7fvPaztT/GZdE/fsdM4rCeXM6f5qpRflAedIqSnWZ0juDGvKDt+Vz7BS9Yh0VxSrVSUOHB0diBePMMQmvbePv0k/zmFm/WZqk6AOrPMMK5tCieqJb4tXMCGY/gE52pkvl/1vm/LVY4tolj49gMakpxCbpid0ZeGcjMqyEbeB5fxWLAJJENud6vV8P/bNlD9qHEb6NhOPoES365vKdp7tXiG/YjsQstd9pDFCpSkOAhN5UPUW2+Fu+ZJPh6SJvBWApBDWRuqyAiQhzb1/1/pM0Uwpmc4Fk29lk1qV1zsaWuVTvKoSafb1Te+Oz1JJ/NEVA7qEh/Rq24y9bEMfNJ5dTUKS3dqEo+XEByjO+cWur2j5XlNrdjZoCXgcN4fokL/zT+2JzQKXWsUlGpJovXD9c+TYGy4TdZzeGTc2Gho=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
