travis:
  secure:
    BINSTAR_TOKEN: Ihtdm3ZtAlQ6jX+ELNh6gAV9ZVG0JsqZvfzuoKll5WPIbJ79a5nnj4Slt+vuX/xSoqLYzI1mpZyT8Dm/aOvwuuH3ztRgDevUhlCaMDGfxlNzTcXEmvTgFqRmJJQbw53VLCCEOFHBTa2d837ccvREnb2fw421C04YMmZulW/x3OvxaiGAB720vyM2fOTBGGbJ8udot+Rjv9AmNLbBAFnjX+qoLBA5+nxxB1WHVcpqikOl+7xlNydSbAAaYDtI9paREBZO9KazZk2nPyJkGvjxBBylsP5T2ayLrfJDa0IeBRZdtn12eM7Ddc//jqtYSSv1NVSRzgQJjljf96z+HVmWb0pAJ4VH8W64EFiPMpSr7toJ0fKQi3SBDyJS4c7aH8Fm2ShjRKIsqYdocHRhJO2Xt2NGnvWwTdjTdum6hc086xbnGE93Vsd+U2H/u5SVKyYVEOKY4cYfFqhFlJpyA7OcWYWqhDwSdYz6r+BvobprRiodX4kyLoX13EexvVC4Yg6CLemHTEuiBt6L6QiTc8JLMFNN0erdRmvzy5PXfm1oS9/l+FQCRYjTloScvd4KAwGCdOLWgcnm+uYPUXVEo6fEzdY95K3vtjv9ruuF9yrGxfKI3FSrNSSCAvtYj7ssW5Ono1Ng491R51rQNHK2OyMCvHGLKajpre587ubk6231uds=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
