travis:
  secure:
    BINSTAR_TOKEN: rvl6wn4eUSIZGSnEAAr0YncK+d92B1GqlSKf2YUmXqGSHuguR3fyAJdwtmputziOTOfiyAE1sSXyaOFQQcAygwI0swYNxkqTrk3to58/pNzcS22jInsfr59NAEs7bLUZNFohoXforyGBJao+wu+p5xXu/k/gX+ErFtHV7e2yeqs/SJzFwoTscYn/s0mT7avWv9xmakJ6KbyCPufdS5HLhnhKrx5R9nF/R60zVJ4l0IOovxdKFYLbDp6BQ+86fVNweRi4AQVO5ztnWyWmB8KCYQLaYK42wuhDRg01PaomZ5+LwHwrVxruN+iGzdS03031cGmWhRgSQsBSWJB0N/X0HmfXKMnK99RHC6xHTJ4riGqS41PHfJL7KDSKL9HmsRJH7LIPfLWYk0VdSz/FpGHe83yU3orys5lgJ6qaaxyO10hi3CDy91Ra4Q2e1r10Ahj7aQNBXVCsnDygeoLzk887UpaHW9y/euZwFxdlJmNfz2SEM64pAZwaFVDAFLRm0HHOWr1HlyrPsnmI1vZqm3+op+TaAoUQFLHHe2eaQYqBCSe2IYQjU+qcfjpyv3RzIC9WVjhe/bV8jiVhJWIPctBhjI/5TfUw30+3JlPAPCwgS1IgRON0s94fI2k3Om64exge8fOYuIAsTF2DhWpevYOK0dRzAsJtot7jMmBpIIYHO4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
